import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Zul</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>I Love You</h1>
<<<<<<< HEAD
=======
				<img src="/heart.png" alt="" />
>>>>>>> 67f5115de1d55088e8a39f4530acc7afe8b93fac
			</main>
		</div>
	);
};

export default Home;
